### ISSUE TITLE
Wrong hitTest in header

### ISSUE THREAD

**Issue by Amir-P** [NikolayNIK/material_table_view#7]
Steps to reproduce:

1. Wrap each column in header with an `InkWell` widget
2. Hover mouse to check splash for each column and their region
3. Do some random horizontal scrolling
4. Hover mouse to check columns again

https://github.com/NikolayNIK/material_table_view/assets/8766492/68dbb126-11b4-4dd3-916d-5bb2b44de8d2

**Comment by NikolayNIK** [comment]
Thanks for pointing this out!

**Comment by Amir-P** [comment]
Are you able to find the root of this issue? I have some free time to work on it and it's kinda blocking for me. I want to help fixing it but I can't find what is causing this issue.
BTW, thanks for this great library. @NikolayNIK

**Comment by NikolayNIK** [comment]
> Are you able to find the root of this issue?

Yeah, so it seems like `TableViewRow`s children layout information used in the hit tests (e.g. `_TableViewCellParentData.offset`) is not currently updating every time the horizontal scroll offset changes. So either `parent.markNeedsLayout();` call is needed [here](https://github.com/NikolayNIK/material_table_view/blob/8b7d3eb36c3a878b48c7b228888bae55fb5f2587/lib/src/table_row.dart#L194) or [`hitTestChildren` implementation](https://github.com/NikolayNIK/material_table_view/blob/8b7d3eb36c3a878b48c7b228888bae55fb5f2587/lib/src/table_row.dart#LL159C8-L159C8) needs to use `position` field instead of `offset`. I think former is the safer option/

**Comment by Amir-P** [comment]
Thanks for your response! I'll give it a try now. @NikolayNIK

**Comment by NikolayNIK** [comment]
Also related to hit testing is the issue of scrolled cells not respecting the clip path during hit tests, leading to almost entirely clipped cells still participating (and often taking precedence over actually visible ones). To avoid this, the clipPath formed [here](https://github.com/NikolayNIK/material_table_view/blob/8b7d3eb36c3a878b48c7b228888bae55fb5f2587/lib/src/table_section.dart#L155) needs to be passed down to `TableRow` for hit testing.

**Comment by NikolayNIK** [comment]
I should be able to fix both of these myself and publish a fix by tomorrow, but I'd be grateful if you can submit a pull request in the meantime

**Comment by Amir-P** [comment]
> `parent.markNeedsLayout();` call is needed [here](https://github.com/NikolayNIK/material_table_view/blob/8b7d3eb36c3a878b48c7b228888bae55fb5f2587/lib/src/table_row.dart#L194) 
Doing so, did the trick!

> To avoid this, the clipPath formed [here](https://github.com/NikolayNIK/material_table_view/blob/8b7d3eb36c3a878b48c7b228888bae55fb5f2587/lib/src/table_section.dart#L155) needs to be passed down to TableRow for hit testing.
`TableViewRow` is not the direct descendant of `TableSection`. Isn't it easier to just check if gesture position is inside of `clipPath` in `_RenderTableSection.hitTest`?

**Comment by NikolayNIK** [comment]
> `TableViewRow` is not the direct descendant of `TableSection`. Isn't it easier to just check if gesture position is inside of `clipPath` in `_RenderTableSection.hitTest`? Something like this:
> 
> ```dart
>   @override
>   bool hitTest(BoxHitTestResult result, {required Offset position}) {
>     if (!clipPath.contains(position)) {
>       return false;
>     }
>     return super.hitTest(result, position: position);
>   }
> ```

I think it would make it so the rows (and its cells) can only be clicked in the scrolled section and not outside of it. Only the scrolled cells should affected by that clipping (that variable should have been named better). This is why I thought of somehow passing that Path to `TableViewRow` so it can figure out which cells should be affected.

**Comment by Amir-P** [comment]
> I think it would make it so the rows (and its cells) can only be clicked in the scrolled section and not outside of it.

Isn't it what we expect to happen? I got confused a bit.

**Comment by NikolayNIK** [comment]
> > I think it would make it so the rows (and its cells) can only be clicked in the scrolled section and not outside of it.
> 
> Isn't it what we expect to happen? I got confused a bit.

No, we still want frozen cells and the row underneath to be clickable. Let me try to explain. At any time there are zero or more cells that are frozen at the edge. Other cells can have arbitrary horizontal offset and so are destined to overlap with the frozen ones. To prevent that overlapping, the whole scrolled section get clipped using the wiggly path in question. Now, when it comes to hit testing, right now it doesn't take into account clipping so the frozen cells can win the hit test even if they clearly shouldn't be, like this: 
![image](https://github.com/NikolayNIK/material_table_view/assets/10992825/48956d8b-4027-463d-93bf-9bdea68e1958)

Here, the 30th column wins the hit test even though it's clipped off under the cursor

**Comment by NikolayNIK** [comment]
@Amir-P, I'm going to take on the last part now, if you don't mind

**Comment by Amir-P** [comment]
> @Amir-P, I'm going to take on the last part now, if you don't mind

Sure. I'm not familiar with the codebase hence I didn't do anything on the remaining part of the problem. Thanks for taking the time to fix it completely. @NikolayNIK

**Comment by NikolayNIK** [comment]
Fixed the last part with e0f55df0bfee05007384e219ac8162e9ced1aff5
